train:
  epochs: 1 # TODO: change to 5 later
  layers: 'heads'
  model-config:
    NAME: 'kangaroo_cfg'
    NUM_CLASSES: 2
    STEPS_PER_EPOCH: 5 # this for testing only
    # STEPS_PER_EPOCH: 131 
    BACKBONE: 'resnet101'
    IMAGES_PER_GPU: 2
    GPU_COUNT: 1
  weights:
    init: 'model/transfer/mask_rcnn_coco.h5'
    exclude: 
      - 'mrcnn_class_logits'
      - 'mrcnn_bbox_fc'
      - 'mrcnn_bbox'
      - 'mrcnn_mask'
test:
  override-model-configs:
    USE_MINI_MASK: False
    IMAGES_PER_GPU: 1
